name: basic-ci
on:
  push:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Python 3
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
          cache: pip
          cache-dependency-path: setup.py
      - name: Install dependencies
        run: |
          # using the --upgrade and --upgrade-strategy eager flags ensures that
          # pip will always install the latest allowed version of all
          # dependencies, to make sure the cache doesn't go stale
          pip install --upgrade --upgrade-strategy eager .
          pip install black isort flake8
      - name: Lint
        run: |
          black --check my_package/
          isort --check my_package/
          flake8 my_package/ --max-complexity 10

  tests:
    needs: lint
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.8, 3.9, '3.10']
    steps:
      - uses: actions/checkout@v3
      - name: Install Python 3
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip
          cache-dependency-path: setup.py
      - name: Install dependencies
        run: |
          # using the --upgrade and --upgrade-strategy eager flags ensures that
          # pip will always install the latest allowed version of all
          # dependencies, to make sure the cache doesn't go stale
          pip install --upgrade --upgrade-strategy eager .
          pip install pytest
      - name: Run pytest
        run: pytest tests/
